function [IM, sigma, LnIM] = calculate_GMPM_for_unique_rows( ...
    uniqueRows, n_GMPM, GMPM_types, ...
    Vs30, Z1o0, Z2o5, Region, Fault_Type_name, ...
    FVS30, fas, HW, T, Dip, lambda_input)

%%% This function calculates GMPMs only for unique GMPM input rows.
%%% It can be used for both MS and AS.
n_uniqueRows = size(uniqueRows,1);
IM = zeros(n_uniqueRows, n_GMPM);
sigma = zeros(n_uniqueRows, n_GMPM);

for iii = 1 : n_uniqueRows

    [rup] = NGA_GMPM_parameter_estimation_accurate( ...
        uniqueRows(iii,1), ...
        uniqueRows(iii,2), ...
        uniqueRows(iii,3), ...
        uniqueRows(iii,4), ...
        uniqueRows(iii,5), ...
        uniqueRows(iii,6), ...
        uniqueRows(iii,7), ...
        Dip, ...
        uniqueRows(iii,8), ...
        lambda_input, ...
        Vs30, Z1o0, Z2o5, ...
        Region, Fault_Type_name, FVS30, fas, HW);

    for j = 1 : n_GMPM

        if strcmp(GMPM_types{j},'BSSA_2014')

            [IM(iii,j), sigma(iii,j)] = BSSA_2014_nga( ...
                rup.M, T, rup.Rjb, rup.Fault_Type, ...
                rup.Region, rup.Z1o0, rup.Vs30);

        end

        if strcmp(GMPM_types{j},'CB_2014')

            [IM(iii,j), sigma(iii,j)] = CB_2014_nga( ...
                rup.M, T, rup.Rrup, rup.Rjb, rup.Rx, ...
                rup.W, rup.Ztor, rup.Zbot, rup.Dip_degree, ...
                rup.lambda_degree, rup.Fhw, rup.Vs30, ...
                rup.Z25, rup.Zhyp, rup.Region);

        end

        if strcmp(GMPM_types{j},'CY_2014')

            [IM(iii,j), sigma(iii,j)] = CY_2014_nga( ...
                rup.M, T, rup.Rrup, rup.Rjb, rup.Rx, ...
                rup.Ztor, rup.Dip_degree, rup.lambda_degree, ...
                rup.Z1o0, rup.Vs30, rup.Fhw, rup.FVS30, ...
                rup.Region);

        end

        if strcmp(GMPM_types{j},'ASK_2014')

            [IM(iii,j), sigma(iii,j)] = ASK_2014_nga( ...
                rup.M, T, rup.Rrup, rup.Rjb, rup.Rx, rup.Ry, ...
                rup.Ztor, rup.Dip_degree, rup.lambda_degree, ...
                rup.fas, rup.Fhw, rup.W, rup.Z1o0, ...
                rup.Vs30, rup.FVS30, rup.Region);

        end

    end

end

LnIM = log(IM);

end